MVC/SimpleMVC_UnitTests_xUnit/SimpleMVC/Models/Entities/Car.cs
using System.ComponentModel.DataAnnotations;

namespace SimpleMVC.Models.Entities;

public class Car
{
    [MaxLength(10)]
    public string CarId { get; set; } = "No license number";
    public string Make { get; set; } = "Unknown";
    public string Model { get; set; } = "Unknown";
    public int Year { get; set; }
}

MVC/SimpleMVC_UnitTests_xUnit/SimpleMVC/Models/ErrorViewModel.cs
namespace SimpleMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MVC/SimpleMVC_UnitTests_xUnit/SimpleMVC/Controllers/GarageController.cs
using Microsoft.AspNetCore.Mvc;
using SimpleMVC.Models.Entities;
using SimpleMVC.Repository;

namespace SimpleMVC.Controllers;

public class GarageController : Controller
{
    private readonly ICarRepository _repository;

    public GarageController(ICarRepository repository)
    {
        _repository = repository;
    }

    // Home/Index: GET
    public IActionResult Index()
    {
        var cars = _repository.GetAll();
        
        return View(cars);
    }

    // Create: GET
    public IActionResult Create()
    {
        return View();
    }

    // Create: POST
    [HttpPost]
    public IActionResult Create([Bind("CarId,Make,Model,Year")] Car car)
    {
        try
        {
            if (!ModelState.IsValid) return View();
            
            _repository.Save(car);
            TempData["message"] = $"{car.CarId} has been created!";
            return RedirectToAction("Index");
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            TempData["message"] = "Obs something went wrong!";
            return RedirectToAction("Index");
        }
    }
}

MVC/SimpleMVC_UnitTests_xUnit/SimpleMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SimpleMVC.Models;

namespace SimpleMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MVC/SimpleMVC_UnitTests_xUnit/SimpleMVC/Views/Garage/Create.cshtml
@model SimpleMVC.Models.Entities.Car

@{
    ViewData["Title"] = "Add Car";
}

<div class="row">
    <div class="col-md-4">
        <form method="post">
            <h1>Create</h1>
            <hr />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div>
                <label asp-for="CarId">License:</label>
                <input asp-for="CarId" class="form-control"/>
                <span asp-validation-for="CarId" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Make">Make:</label>
                <textarea asp-for="Make" class="form-control"></textarea>
                <span asp-validation-for="Make" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Model">Model:</label>
                <textarea asp-for="Model" class="form-control"></textarea>
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div>
                <label asp-for="Year">Year:</label>
                <textarea asp-for="Year" class="form-control"></textarea>
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Add Car</button>
        </form>
    </div>
</div>

@section Scripts
    {@{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}}

MVC/SimpleMVC_UnitTests_xUnit/SimpleMVC/Views/Garage/Index.cshtml
@{
    ViewData["Title"] = "My Garage";
}

<div class="text-center">
    <h1 class="display-4">Cars</h1>
    @if (Model == null || Model?.Count == 0)
    {
        <p>No cars found in your garage.</p>
    } 
    else
    {
        <table class="table table-striped table-bordered">
            <thead style="background-color: #930606; color: #fff;">
                <tr>
                    <td>License</td>
                    <td>Make</td>
                    <td>Model</td>
                    <td>Year</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var c in Model)
                {
                    <tr>
                        <td>@c.CarId</td>
                        <td>@c.Make</td>
                        <td>@c.Model</td>
                        <td>@c.Year</td>
                    </tr>
                }
            </tbody>
        </table>
    }

    <a href="@Url.Action("Create", "Garage")" class="btn btn-primary">Create</a>
</div>

MVC/SimpleMVC_UnitTests_xUnit/SimpleMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SimpleMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/SimpleMVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SimpleMVC</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Garage" asp-action="Index">Garage</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @if (TempData["message"] != null) {
        <div class="alert alert-success">
            <button type="button" class="close" data-bs-dismiss="alert">x</button>
            @TempData["message"]
        </div>
        }
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - SimpleMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>